### ISSUE TITLE
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: GitHubError(GitHub { source: GitHubError { documentation_url: Some("https://docs.github.com/rest/reference/pulls#list-reviews-for-a-pull-request"), errors: None, message: "Not Found" }, backtrace: Backtrace(   0: <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate

### ISSUE THREAD

**Issue by MarcoFalke** [MarcoFalke/DrahtBot#24]
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: GitHubError(GitHub { source: GitHubError { documentation_url: Some("https://docs.github.com/rest/reference/pulls#list-reviews-for-a-pull-request"), errors: None, message: "Not Found" }, backtrace: Backtrace(   0: <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.3/src/backtrace_shim.rs:15:19
      octocrab::map_github_error::{{closure}}
             at /root/.cargo/git/checkouts/octocrab-800d493a1be2acf4/99872f2/src/lib.rs:227:24
   1: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
   2: octocrab::api::pulls::PullRequestHandler::http_get::{{closure}}
             at /root/.cargo/git/checkouts/octocrab-800d493a1be2acf4/99872f2/src/api/pulls.rs:363:84
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
   4: octocrab::api::pulls::PullRequestHandler::list_reviews::{{closure}}
             at /root/.cargo/git/checkouts/octocrab-800d493a1be2acf4/99872f2/src/api/pulls.rs:239:40
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
   6: webhook_features::features::summary_comment::refresh_summary_comment::{{closure}}
             at src/features/summary_comment.rs:212:53
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
   8: <webhook_features::features::summary_comment::SummaryCommentFeature as webhook_features::features::Feature>::handle::{{closure}}
             at src/features/summary_comment.rs:73:62
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/future.rs:124:9
  11: webhook_features::emit_event::{{closure}}
             at src/main.rs:94:47
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
  13: <webhook_features::postreceive_handler as actix_web::service::HttpServiceFactory>::register::postreceive_handler::{{closure}}
             at src/main.rs:69:34
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
  15: actix_web::handler::handler_service::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.2.1/src/handler.rs:105:32
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/future.rs:124:9
  18: <actix_web::resource::Resource<T> as actix_web::service::HttpServiceFactory>::register::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.2.1/src/resource.rs:383:27
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/future.rs:124:9
  21: <actix_service::map_err::MapErrFuture<A,Req,F,E> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-2.0.2/src/map_err.rs:99:9
  22: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.2.2/src/h1/dispatcher.rs:470:27
  23: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.2.2/src/h1/dispatcher.rs:1143:43
  24: <actix_http::service::HttpServiceHandlerResponse<T,S,B,X,U> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.2.2/src/service.rs:716:45
  25: <actix_service::and_then::AndThenServiceResponse<A,B,Req> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-2.0.2/src/and_then.rs:114:37
  26: <actix_server::service::StreamService<S,I> as actix_service::Service<(actix_server::worker::WorkerCounterGuard,actix_server::socket::MioStream)>>::call::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.1.1/src/service.rs:75:30
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
  28: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/core.rs:208:17
  29: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/loom/std/unsafe_cell.rs:14:9
  30: tokio::runtime::task::core::Core<T,S>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/core.rs:197:13
  31: tokio::runtime::task::harness::poll_future::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:483:19
  32: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/panic/unwind_safe.rs:271:9
  33: std::panicking::try::do_call
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:492:40
  34: __rust_try
  35: std::panicking::try
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:456:19
  36: std::panic::catch_unwind
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panic.rs:137:14
  37: tokio::runtime::task::harness::poll_future
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:471:18
  38: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:107:27
  39: tokio::runtime::task::harness::Harness<T,S>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:61:15
  40: tokio::runtime::task::raw::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/raw.rs:194:5
  41: tokio::runtime::task::raw::RawTask::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/raw.rs:134:18
  42: tokio::runtime::task::LocalNotified<S>::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/mod.rs:430:9
  43: tokio::task::local::LocalSet::tick::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:616:63
  44: tokio::runtime::coop::with_budget
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
      tokio::runtime::coop::budget
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
      tokio::task::local::LocalSet::tick
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:616:31
  45: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:928:16
  46: tokio::task::local::LocalSet::with::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:685:13
  47: std::thread::local::LocalKey<T>::try_with
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/thread/local.rs:442:16
  48: std::thread::local::LocalKey<T>::with
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/thread/local.rs:418:9
  49: tokio::task::local::LocalSet::with
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:668:9
  50: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:914:9
  51: tokio::task::local::LocalSet::run_until::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:574:18
  52: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
  53: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/future.rs:124:9
  54: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:531:57
  55: tokio::runtime::coop::with_budget
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
      tokio::runtime::coop::budget
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:531:25
  56: tokio::runtime::scheduler::current_thread::Context::enter
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:340:19
  57: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:530:36
  58: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:601:57
  59: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/macros/scoped_tls.rs:61:9
  60: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:601:27
  61: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:520:19
  62: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:154:24
  63: tokio::runtime::runtime::Runtime::block_on
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/runtime.rs:279:47
  64: tokio::task::local::LocalSet::block_on
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:535:9
  65: actix_rt::runtime::Runtime::block_on
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.7.0/src/runtime.rs:80:9
  66: actix_rt::arbiter::Arbiter::with_tokio_rt::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.7.0/src/arbiter.rs:144:21
  67: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/sys_common/backtrace.rs:122:18
  68: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/thread/mod.rs:498:17
  69: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/panic/unwind_safe.rs:271:9
  70: std::panicking::try::do_call
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:492:40
  71: __rust_try
  72: std::panicking::try
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:456:19
  73: std::panic::catch_unwind
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panic.rs:137:14
  74: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/thread/mod.rs:497:30
  75: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/ops/function.rs:227:5
  76: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/alloc/src/boxed.rs:1861:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/alloc/src/boxed.rs:1861:9
      std::sys::unix::thread::Thread::new::thread_start
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/sys/unix/thread.rs:108:17
  77: <unknown>
  78: <unknown>
) })', src/main.rs:69:41

**Comment by MarcoFalke** [comment]
Looks like this happens in `pulls_api.list_reviews(pr_number).await`

**Comment by MarcoFalke** [comment]
Let's print the pr_number: 284b48ecdd8a00a2bab5964b42a7f74e997d8dfa

**Comment by MarcoFalke** [comment]
Refresh summary comment for 21928

thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: GitHubError(Serde { source: Error("invalid type: null, expected struct User", line: 0, column: 0), backtrace: Backtrace(   0: <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate

**Comment by aureleoules** [comment]
This is a different error, right?

**Comment by MarcoFalke** [comment]
Maybe. Though, it was in the same line, so it is likely the same error.
