### ISSUE TITLE
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: GitHubError(GitHub { source: GitHubError { documentation_url: Some("https://docs.github.com/rest/reference/pulls#request-reviewers-for-a-pull-request"), errors: None, message: "Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the bitcoin/bitcoin repository." }, backtrace: Backtrace(   0: <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate

### ISSUE THREAD

**Issue by MarcoFalke** [MarcoFalke/DrahtBot#29]
Event: https://github.com/bitcoin/bitcoin/pull/26889#pullrequestreview-1299555883

Code:
```
at src/features/summary_comment.rs:284:61
        pulls_api
            .request_reviews(pr_number, stale_reviewers, [])
            .await?;
```

Log:

```
Refresh summary comment for 26889
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: GitHubError(GitHub { source: GitHubError { documentation_url: Some("https://docs.github.com/rest/reference/pulls#request-reviewers-for-a-pull-request"), errors: None, message: "Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the bitcoin/bitcoin repository." }, backtrace: Backtrace(   0: <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.3/src/backtrace_shim.rs:15:19
      octocrab::map_github_error::{{closure}}
             at /root/.cargo/git/checkouts/octocrab-800d493a1be2acf4/64f22ab/src/lib.rs:227:24
   1: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
   2: octocrab::Octocrab::post::{{closure}}
             at /root/.cargo/git/checkouts/octocrab-800d493a1be2acf4/64f22ab/src/lib.rs:683:59
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
   4: octocrab::api::pulls::PullRequestHandler::request_reviews::{{closure}}
             at /root/.cargo/git/checkouts/octocrab-800d493a1be2acf4/64f22ab/src/api/pulls.rs:291:40
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
   6: webhook_features::features::summary_comment::refresh_summary_comment::{{closure}}
             at src/features/summary_comment.rs:284:61
...

**Comment by MarcoFalke** [comment]
https://github.com/XAMPPRocky/octocrab/blob/fb2eaed4464730721c31a76f38e3b334926f28e5/src/api/pulls.rs#L291

https://github.com/XAMPPRocky/octocrab/blob/fb2eaed4464730721c31a76f38e3b334926f28e5/src/lib.rs#L227

**Comment by MarcoFalke** [comment]
Looks like yesterday the behaviour was different: https://github.com/bitcoin/bitcoin/pull/26889#event-8512666454

:man_shrugging:
